# Site settings
title: City of Codes
SEOTitle: BoYa的博客 | City of Codes
header-img: img/post-bg-desk.jpg
email: masteryhx@gmail.com
description: "If you have the opportunity to understand your life in advance, knowing that youth is only these days, I wonder if you will care about things that the world wants you to care about."
keyword: "BoYa,masteryhx,Hangxiang Yu,俞航翔,Java,Flink"
url: "https://masteryhx.github.io"          
baseurl: ""
github_repo: "https://github.com/masteryhx/masteryhx.github.io.git"

# Sidebar settings
sidebar: true                           
sidebar-about-description: "You are your own boss!"
sidebar-avatar: /img/about-myself.jpeg

# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     俞航翔
github_username:    masteryhx    
# facebook_username: 
# jianshu_username:   
#twitter_username: 




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: masteryhx

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f094b8e1ebc887c8f7dc                            #生成的clientID
  clientSecret: 586e466182de2968e9791d1b1a73c9649896c41e   #生成的clientSecret
  repo: masteryhx.github.io    #仓库名称
  owner: masteryhx    #github用户名
  admin: masteryhx
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b041adc97e17a0cc2627c6d38f4eae81 

# Google Analytics
ga_track_id: 'G-BELD06DD35'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 域名或auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    }
]

# theme: jekyll-theme-slate
